#!/bin/bash

source $PACKMAN_SCRIPTS/bash_utils.sh

function packman_help
{
    notice "PACKMAN command usage:"
    echo
    echo -e "- packman $(add_color collect 'bold')"
    echo
    echo -e "\tcollect packages from internet"
    echo
    echo -e "- packman $(add_color install 'bold') <config_file>"
    echo
    echo -e "\tinstall the packages"
    echo
    echo -e "- packman $(add_color setup_env 'bold') <config_file>"
    echo
    echo -e "\tsetup the BASH environment"
    echo
    echo -e "- packman $(add_color update 'bold')"
    echo
    echo -e "\tupdate PACKMAN (need cloned through GIT)"
    echo
    echo -e "- packman $(add_color help 'bold')"
    echo
    echo -e "\tprint this help"
    echo
}

case $1 in
"collect")
    "$PACKMAN_SCRIPTS/collect.sh"
    ;;
"install")
    "$PACKMAN_SCRIPTS/install.sh" $2
    ;;
"setup_env")
    "$PACKMAN_SCRIPTS/setup_env.sh" $2
    ;;
"update")
    "$PACKMAN_SCRIPTS/update.sh"
    ;;
"help")
    packman_help
    ;;
*)
    packman_help
    ;;
esac
