#!/bin/bash

source $PACKMAN_SCRIPTS/bash_utils.sh

function packman_help
{
    notice "PACKMAN command usage:"
    echo
    echo -e "- packman $(add_color collect 'bold') <config_file>"
    echo
    echo -e "\tcollect packages from internet"
    echo
    echo -e "- packman $(add_color install 'bold') <config_file>"
    echo
    echo -e "\tinstall the packages"
    echo
    echo -e "- packman $(add_color setup_env 'bold') <config_file>"
    echo
    echo -e "\tsetup the BASH environment"
    echo
    echo -e "- packman $(add_color update 'bold')"
    echo
    echo -e "\tupdate PACKMAN (need cloned through GIT)"
    echo
    echo -e "- packman $(add_color help 'bold')"
    echo
    echo -e "\tprint this help"
    echo
}

function create_config_template
{
    config_file=$1
    if [[ ! -f $config_file ]]; then
cat <<EOF > $config_file
package_root = <where_is_packages>
build_root = <where_to_build_packages>
install_root = <where_to_install>
c_compiler = gcc
cxx_compiler = g++
fortran_compiler = gfortran
#include_packages = all
#exclude_packages = none
EOF
    fi
}
export -f create_config_template

case $1 in
"collect")
    "$PACKMAN_SCRIPTS/collect.sh" $2
    ;;
"install")
    "$PACKMAN_SCRIPTS/install.sh" $2
    ;;
"setup_env")
    "$PACKMAN_SCRIPTS/setup_env.sh" $2
    ;;
"update")
    "$PACKMAN_SCRIPTS/update.sh"
    ;;
"help")
    packman_help
    ;;
*)
    packman_help
    ;;
esac
